#pragma kernel CSMain

int GRID_RES;
float gravity;
float dt;

RWStructuredBuffer<float> velY;

uint VelYIndex(uint i, uint j, uint k)
{
    return i + j * (uint)GRID_RES + k * (uint)GRID_RES * (uint)(GRID_RES + 1);
}

[numthreads(8, 8, 8)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint)GRID_RES || id.y >= (uint)(GRID_RES + 1) || id.z >= (uint)GRID_RES)
    {
        return;
    }

    uint index = VelYIndex(id.x, id.y, id.z);
    velY[index] -= gravity * dt;
}
